# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9f03b09ef8a61fdf1ce8c41220bbd7ad"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "boa-home-task-GMD"
handle = "boa-home-task-gmd"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
